#!/usr/bin/python
import argparse
import sys
import io
import os

def getTemplatePost():
    homePath = os.path.expanduser('~')
    billingCodePath = os.path.join(homePath, '.gitCommitTemplatePost')
    if not os.path.exists(billingCodePath):
        return ''
    with io.open(billingCodePath, 'r') as stream:
        return stream.readlines()

def getExistingLines(commitFilePath):
    with io.open(commitFilePath, 'r') as stream:
        return stream.readlines()


def writeCommitFile(linesToWrite, commitFilePath):
    with io.open(commitFilePath, 'wb') as outStream:
        for eachLine in linesToWrite:
            outStream.write(eachLine)

def parseArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument('allArgs', nargs="*")
    args = parser.parse_args()
    return args.allArgs[0] #the first arg is always the commit file path

def main():
    commitFilePath = parseArgs()
    linesToWrite = getExistingLines(commitFilePath)
    linesToWrite += getTemplatePost()
    writeCommitFile(linesToWrite, commitFilePath)


if __name__ == '__main__':
    main()
